### ISSUE TITLE
Plan out electronics for kitchen

### ISSUE THREAD

**Issue by sarahmonster** [tofumatt/the-flat-that-matt-and-sarah-rebuilt#38]
We'll need to sort out any required electric work beforehand.

- [x] put together a lighting plan (see also #45)
- [x] plan socket locations 
- [ ] purchase said sockety supplies
- [x] find out if any of our appliances (notably the cooker) will require extra amps
- [x] contact an electrician for a quote

**Comment by tofumatt** [comment]
Plan is good and nearly all wiring is roughed in.

Only thing left to do is purchase a few odd sockets for things like the 32A + outlet cooker box.

**Comment by sarahmonster** [comment]
Yay! Make me a list tomorrow, assign this to me, and I'll get it sorted.

**Comment by tofumatt** [comment]
For the kitchen, we need:

* 5 x 2-gang 13A outlet covers. I think we already have enough of these, but the black ones we use in the bedroom work for me. I know in general I'm not a huge fan of the USB sockets, but *if* you found black ones that matched/looked good with USB sockets on them that might not be bad for the bar area. Something in here could be nice: https://www.diy.com/departments/electrical/switches-dimmers-sockets/usb-sockets/DIY1441351.cat
* 1 x 45A + 13A socket fused cooker switch: Basically something like this: https://www.diy.com/departments/nexus-45a-double-pole-cooker-switch-socket-with-13-a-switch-socket/191342_BQ.prd Get whatever style you want (ideally it should match the rest of the kitchen).

That really should be it, because I'll ask the electricians to supply the out-of-sight covers for things like the dishwasher, washing machine, Kitchen Kicker™, and range hood.

--------

While we're ordering these we'll want to replace the RCDs in the hallway with fused connection units (FCUs) with a switch:

* 2 FCUs – these will replace the RCDs for the bathroom's towel rail and underfloor heating in the hallway

https://www.screwfix.com/c/electrical-lighting/switches-sockets/cat830530?switchessocketsproducttype=fcu%7Cfused_spur#category=cat830530&parentcolour=white&switchessocketsproducttype=fcu%7Cfused_spur&page_size=100 something in that set works.

Personally to match the white I'd say: https://www.screwfix.com/p/mk-13a-dp-switched-fused-connection-unit-with-flex-outlet-white/13479

If you wanted to paint the boxes black we could get: https://www.screwfix.com/p/british-general-13a-1-gang-switched-fused-connection-unit-matt-black/30604

In the future it might be nice to relocate the switch up the wall for the towel rail, but I'm not sure what kind of wall surgery that requires.

**Comment by sarahmonster** [comment]
For reference, this is what we use elsewhere in the house:

- dual-gang outlets: https://www.diy.com/departments/nexus-13a-black-cast-black-switched-twin-socket-pack-of-5/276690_BQ.prd
- shaver socket: https://www.amazon.co.uk/dp/B00P9KO2RI/ref=pe_385721_37038051_TE_3p_dp_1

This may match: https://www.diy.com/departments/nexus-13a-black-matt-switched-socket-2-x-usb/570944_BQ.prd (we can look at it directly in person if we take a B&Q trip!)

For the cooker, this may work: https://www.directelectrical.co.uk/products/Switches+%26+Sockets/Nexus+Metal/Matt+Black+%26+Chrome+45A+Cooker+Control+Unit+w%2F+13A+Switch+Black+Insert/360156501

Do we also need two one-gang light switches?

**Comment by tofumatt** [comment]
Oh, fair point. We need 2x single switch light switches but we have those already.

**Comment by tofumatt** [comment]
I like those other options too. I say :shipit:

**Comment by sarahmonster** [comment]
Purchased! 

<img width="1118" alt="screenshot 2018-08-29 21 31 54" src="https://user-images.githubusercontent.com/376315/44814232-f44df900-abd3-11e8-9024-a4a4cbd017bd.png">

Also, sidenote:

<img width="478" alt="screenshot 2018-08-29 21 35 19" src="https://user-images.githubusercontent.com/376315/44814240-fc0d9d80-abd3-11e8-8b4c-c2df53bc9916.png">

GREAT WORK SCREWFIX.

I think that means we can close this issue, 🎉.
